[github_app]
pr_commands = ["/describe", "/review", "/improve"]

[pr_description]
publish_title = true
publish_description = true
enable_walkthrough = true
use_description_markers = false

[pr_review]
publish_review = true

[pr_code_suggestions]
publish_suggestions = true
